---
title: "Introduction to the project"
output:
  html_document:
    #css: html-md-01.css
    fig_caption: no
    number_sections: no
    toc: no
    toc_float: false
    collapsed: no
---

```{r set-options, echo=FALSE}
options(width = 105)
knitr::opts_chunk$set(dev='png', dpi=300, cache=TRUE)
pdf.options(useDingbats = TRUE)
```

I am working on building some R and Python packages for both R and Python. The packages are mostly focused on financial time series models such as interest rate models, stochastic volatility models, stochastic conditional duration models, latent factor models including non-linear and non-normal state space models, probabilistic principal component models, and component factor models etc. The final goal is to build a set of packages to tackle those models so people can use them to solve the problems without re-implement the estimation algorithms. 

As these models are time-dependent and sometimes are overparameterized, usual MLE may not help to fit those models. We develop Markov Chain Monte Carlo (MCMC) methods within Bayesian framework. As simulation-based inferences are time-consuming, we first do experimentation in R and Python, and then build packages by rewriting the algorithms in C/C++ to speed up the estimation process. 

This is long journey, please visit us frequently to check the updates.


